trigger:
- main
pool:
 vmImage: ubuntu-lateset

variables:
 buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'